title: Listen definieren
question: |
  Definieren Sie eine Liste namens `meine_lieblinge` mit ihren Lieblingsfilmen.
solution: |
  ```python
  meine_lieblinge = ['Alles steht Kopf', 'Die Schlange im Schatten des Adlers', 'Der Pate']
  ```
