title: Listen manipulieren
question: |
  Karl hat eine Liste mit vier Elementen erstellt und versucht nun, ein neues Element mit der folgenden Syntax hinzuzufügen.
  
  Beschreibe den auftretenden Fehler und erkläre, wie man ihn korrigiert.
  
  ```{ .python .pytutor_button }
  freunde = ['Anna', 'Bernd']
  freunde[2] = 'Clara'
  ```
solution: |
  Es 
  
  ```{ .python .pytutor_button }
  freunde = ['Anna', 'Bernd']
  freunde.append('Clara')
  ```